language: node_js
node_js:
  - "12"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - source

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  keep-history: true
  target-branch: master
  local-dir: dist
  on:
    branch: source